version: 2

models:
  - name: silver_cities
    columns:
      - name: city_id
        tests:
          - not_null
          - unique

      - name: country_id
        tests:
          - not_null

  - name: silver_countries
    columns:
      - name: country_id
        tests:
          - not_null
          - unique

  - name: silver_weather_daily
    columns:
      - name: requested_city
        tests:
          - not_null